services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_DATABASE=goldmanager'
      - 'MARIADB_PASSWORD=mypass'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
      - 'MYSQL_ROOT_HOST=%'
    ports:
      - '3307:3306'
    labels:
     org.springframework.boot.readiness-check.tcp.disable: true
